USE COURSE_LAB2

CREATE TABLE COURSE (
    CID INT IDENTITY(1,1),
    CNAME VARCHAR(50),
    DURATION INT UNIQUE, 
    
    CONSTRAINT PK_Course PRIMARY KEY (CID)
);

CREATE TABLE INSTRUCTOR (
    ID INT IDENTITY(1,1), 
    FNAME VARCHAR(50),
    LNAME VARCHAR(50),
    BD DATE,
    SALARY INT DEFAULT 3000 CHECK (SALARY BETWEEN 1000 AND 5000),
    OVERTIME INT UNIQUE, 
    
    ADDRESS VARCHAR(50) CHECK (ADDRESS IN ('Cairo', 'Alex')), 
    HIREDATE DATE DEFAULT GETDATE(),
    
    NETSALARY AS (SALARY + OVERTIME), 
    AGE AS (YEAR(GETDATE()) - YEAR(BD)), 
    
    CONSTRAINT PK_Instructor PRIMARY KEY (ID)
);

CREATE TABLE LAB (
    CID INT, 
    LID INT IDENTITY(1,1), 
    LOCATION VARCHAR(50),
    CAPACITY INT CHECK (CAPACITY < 20), 
    
    CONSTRAINT PK_Lab PRIMARY KEY (CID, LID),
    
    CONSTRAINT FK_Lab_Course FOREIGN KEY (CID) 
    REFERENCES COURSE(CID) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);

CREATE TABLE COURSE_INSTRUCTOR (
    CID INT, 
    ID INT,  
    CONSTRAINT PK_Course_Instructor PRIMARY KEY (CID, ID),
    CONSTRAINT FK_CI_Course FOREIGN KEY (CID) 
    REFERENCES COURSE(CID) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
    CONSTRAINT FK_CI_Instructor FOREIGN KEY (ID) 
    REFERENCES INSTRUCTOR(ID) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);